package main

import (
	"fmt"
	"sort"
	"strings"
)

const indexHeader = `# Generated by doppel from the files in accounts/. Don't edit this file:
# changes are overwritten. Change accounts with doppel or in accounts/<id>.gitconfig.
`

// includeComment marks the block doppel appends to the global Git config.
const includeComment = "# Added by doppel. Keep this at the end of the file so doppel's accounts take effect."

// quoteValue quotes a Git config value when it would otherwise be misread:
// "#" and ";" start comments, and surrounding spaces are trimmed.
func quoteValue(v string) string {
	if !strings.ContainsAny(v, "#;\"\\") && strings.TrimSpace(v) == v {
		return v
	}
	return `"` + strings.NewReplacer(`\`, `\\`, `"`, `\"`).Replace(v) + `"`
}

// renderIndex generates index.gitconfig: the default account first, then one
// rule per folder from broad to specific, because Git lets the last match
// win. Folders are stored with a trailing "/", which Git extends to match
// every repo inside them.
func renderIndex(env *Env, accounts []*Account) []byte {
	var b strings.Builder
	b.WriteString(indexHeader)
	if def := defaultAccount(accounts); def != nil {
		fmt.Fprintf(&b, "\n# Default account, for repos outside every folder below\n[include]\n\tpath = %s\n",
			quoteValue(env.Shorten(env.AccountPath(def.ID))))
	}

	type rule struct{ folder, id string }
	var rules []rule
	for _, a := range accounts {
		for _, f := range a.Folders {
			rules = append(rules, rule{f, a.ID})
		}
	}
	sort.SliceStable(rules, func(i, j int) bool {
		di, dj := env.folderDepth(rules[i].folder), env.folderDepth(rules[j].folder)
		if di != dj {
			return di < dj
		}
		return rules[i].folder < rules[j].folder
	})

	condition := "gitdir:"
	if env.CaseInsensitive() {
		condition = "gitdir/i:"
	}
	if len(rules) > 0 {
		b.WriteString("\n# Folder rules, from broad to specific (the last match wins)\n")
	}
	for _, r := range rules {
		fmt.Fprintf(&b, "[includeIf \"%s%s\"]\n\tpath = %s\n", condition, r.folder,
			quoteValue(env.Shorten(env.AccountPath(r.id))))
	}
	return []byte(b.String())
}

// includeBlock is what doppel appends to the global Git config.
func includeBlock(env *Env) string {
	return includeComment + "\n[include]\n\tpath = " + quoteValue(env.Shorten(env.IndexPath())) + "\n"
}

// includesIndex reports whether a Git config file includes doppel's index.
func includesIndex(env *Env, configPath string) (bool, error) {
	values, err := readConfigFile(configPath)
	if err != nil {
		return false, err
	}
	for _, v := range values["include.path"] {
		if env.SamePath(v, env.IndexPath()) {
			return true, nil
		}
	}
	return false, nil
}

// ensureInclude appends doppel's include block to the end of the global Git
// config unless the file already includes the index. It's appended as text:
// `git config --add` would put it inside an existing [include] section,
// which may not be last.
func ensureInclude(env *Env, plan *Plan) error {
	path := env.GlobalConfigPath()
	staged, err := plan.Stage(path)
	if err != nil {
		return err
	}
	if ok, err := includesIndex(env, staged); err != nil || ok {
		return err
	}
	data, _, err := plan.Content(path)
	if err != nil {
		return err
	}
	text := string(data)
	if text != "" {
		text = strings.TrimRight(text, "\n") + "\n\n"
	}
	return plan.SetContent(path, []byte(text+includeBlock(env)))
}

// removeInclude takes doppel's include out of the global Git config: first
// the exact block doppel appended, then any include of the index that was
// moved or reformatted since. It reports whether anything was removed.
func removeInclude(env *Env, plan *Plan) (bool, error) {
	path := env.GlobalConfigPath()
	data, exists, err := plan.Content(path)
	if err != nil || !exists {
		return false, err
	}
	removed := false
	lines := strings.Split(string(data), "\n")
	for k := 0; k+2 < len(lines); k++ {
		if lines[k] != includeComment || strings.TrimSpace(lines[k+1]) != "[include]" || !isIndexPathLine(env, lines[k+2]) {
			continue
		}
		start, end := k, k+3
		if start > 0 && strings.TrimSpace(lines[start-1]) == "" {
			start-- // the blank line ensureInclude added before the block
		}
		lines = append(lines[:start], lines[end:]...)
		removed = true
		break
	}
	if removed {
		if err := plan.SetContent(path, []byte(strings.Join(lines, "\n"))); err != nil {
			return false, err
		}
	}

	staged, err := plan.Stage(path)
	if err != nil {
		return false, err
	}
	values, err := readConfigFile(staged)
	if err != nil {
		return false, err
	}
	for _, v := range values["include.path"] {
		if !env.SamePath(v, env.IndexPath()) {
			continue
		}
		if err := configFile(staged, "--fixed-value", "--unset-all", "include.path", v); err != nil {
			return false, err
		}
		removed = true
	}
	return removed, nil
}

// isIndexPathLine reports whether a config line is `path = <doppel's index>`.
func isIndexPathLine(env *Env, line string) bool {
	key, value, ok := strings.Cut(line, "=")
	if !ok || !strings.EqualFold(strings.TrimSpace(key), "path") {
		return false
	}
	return env.SamePath(unquoteValue(strings.TrimSpace(value)), env.IndexPath())
}

// unquoteValue reverses quoteValue for a whole-value quoted string.
func unquoteValue(v string) string {
	if len(v) < 2 || v[0] != '"' || v[len(v)-1] != '"' {
		return v
	}
	return strings.NewReplacer(`\\`, `\`, `\"`, `"`).Replace(v[1 : len(v)-1])
}
