package store

import (
	"fmt"
	"sort"
	"strings"

	"github.com/vehkiya/doppel/internal/accounts"
	"github.com/vehkiya/doppel/internal/paths"
)

const indexHeader = `# Generated by doppel from the files in accounts/. Don't edit this file:
# changes are overwritten. Change accounts with doppel or in accounts/<id>.gitconfig.
`

// quoteValue quotes a Git config value when it would otherwise be misread:
// "#" and ";" start comments, and surrounding spaces are trimmed.
func quoteValue(v string) string {
	if !strings.ContainsAny(v, "#;\"\\") && strings.TrimSpace(v) == v {
		return v
	}
	return `"` + strings.NewReplacer(`\`, `\\`, `"`, `\"`).Replace(v) + `"`
}

// RenderIndex generates index.gitconfig: the default account first, then one
// rule per folder from broad to specific, because Git lets the last match
// win. Folders are stored with a trailing "/", which Git extends to match
// every repo inside them.
func RenderIndex(env *paths.Env, list []*accounts.Account) []byte {
	var b strings.Builder
	b.WriteString(indexHeader)
	if def := accounts.Default(list); def != nil {
		fmt.Fprintf(&b, "\n# Default account, for repos outside every folder below\n[include]\n\tpath = %s\n",
			quoteValue(env.Shorten(env.AccountPath(def.ID))))
	}

	type rule struct{ folder, id string }
	var rules []rule
	for _, a := range list {
		for _, f := range a.Folders {
			rules = append(rules, rule{f, a.ID})
		}
	}
	sort.SliceStable(rules, func(i, j int) bool {
		di, dj := env.FolderDepth(rules[i].folder), env.FolderDepth(rules[j].folder)
		if di != dj {
			return di < dj
		}
		return rules[i].folder < rules[j].folder
	})

	condition := "gitdir:"
	if env.CaseInsensitive() {
		condition = "gitdir/i:"
	}
	if len(rules) > 0 {
		b.WriteString("\n# Folder rules, from broad to specific (the last match wins)\n")
	}
	for _, r := range rules {
		fmt.Fprintf(&b, "[includeIf \"%s%s\"]\n\tpath = %s\n", condition, r.folder,
			quoteValue(env.Shorten(env.AccountPath(r.id))))
	}
	return []byte(b.String())
}

// unquoteValue reverses quoteValue for a whole-value quoted string.
func unquoteValue(v string) string {
	if len(v) < 2 || v[0] != '"' || v[len(v)-1] != '"' {
		return v
	}
	return strings.NewReplacer(`\\`, `\`, `\"`, `"`).Replace(v[1 : len(v)-1])
}
