package store

import (
	"fmt"
	"os"
	"strings"

	"github.com/vehkiya/doppel/internal/accounts"
	"github.com/vehkiya/doppel/internal/git"
	"github.com/vehkiya/doppel/internal/paths"
)

const indexHeader = `# Generated by doppel from the files in accounts/. Don't edit this file:
# changes are overwritten. Change accounts with doppel or in accounts/<id>.gitconfig.
`

// quoteValue quotes a Git config value when it would otherwise be misread:
// "#" and ";" start comments, and surrounding spaces are trimmed.
func quoteValue(v string) string {
	if !strings.ContainsAny(v, "#;\"\\") && strings.TrimSpace(v) == v {
		return v
	}
	return `"` + strings.NewReplacer(`\`, `\\`, `"`, `\"`).Replace(v) + `"`
}

// renderIndex generates index.gitconfig: where Git finds allowed signers
// (when signersFile isn't ""), the default account, then the folder rules in
// accounts.FolderRules order. Folders are stored with a trailing "/", which
// Git extends to match every repo inside them.
func renderIndex(env *paths.Env, list []*accounts.Account, signersFile string) []byte {
	var b strings.Builder
	b.WriteString(indexHeader)
	if signersFile != "" {
		fmt.Fprintf(&b, "\n# The signing keys Git trusts when it verifies signatures\n[gpg \"ssh\"]\n\tallowedSignersFile = %s\n",
			quoteValue(env.Shorten(signersFile)))
	}
	if def := accounts.Default(list); def != nil {
		fmt.Fprintf(&b, "\n# Default account, for repos outside every folder below\n[include]\n\tpath = %s\n",
			quoteValue(env.Shorten(env.AccountPath(def.ID))))
	}

	rules := accounts.FolderRules(env, list)
	condition := "gitdir:"
	if env.CaseInsensitive() {
		condition = "gitdir/i:"
	}
	if len(rules) > 0 {
		b.WriteString("\n# Folder rules, from broad to specific (the last match wins)\n")
	}
	for _, r := range rules {
		fmt.Fprintf(&b, "[includeIf \"%s%s\"]\n\tpath = %s\n", condition, r.Folder,
			quoteValue(env.Shorten(env.AccountPath(r.ID))))
	}
	return []byte(b.String())
}

// unquoteValue reverses quoteValue for a whole-value quoted string.
func unquoteValue(v string) string {
	if len(v) < 2 || v[0] != '"' || v[len(v)-1] != '"' {
		return v
	}
	return strings.NewReplacer(`\\`, `\`, `\"`, `"`).Replace(v[1 : len(v)-1])
}

// StaleIndex reports whether index.gitconfig is missing or out of date with
// respect to the account files: if index.gitconfig doesn't exist (when there
// are accounts), was modified before accounts/ or any account file, or its
// content doesn't match the current accounts.
func StaleIndex(env *paths.Env, list []*accounts.Account) bool {
	if len(list) == 0 {
		return paths.FileExists(env.IndexPath())
	}
	indexInfo, err := os.Stat(env.IndexPath())
	if err != nil {
		return true
	}
	indexTime := indexInfo.ModTime()

	if dirInfo, err := os.Stat(env.AccountsDir()); err == nil {
		if dirInfo.ModTime().After(indexTime) {
			return true
		}
	}
	for _, a := range list {
		if a.File != "" {
			if fileInfo, err := os.Stat(a.File); err == nil {
				if fileInfo.ModTime().After(indexTime) {
					return true
				}
			}
		}
	}

	cfg, err := git.ReadConfigFile(env.IndexPath())
	if err != nil {
		return true
	}

	def := accounts.Default(list)
	var wantDef string
	if def != nil {
		wantDef = env.Shorten(env.AccountPath(def.ID))
	}
	haveDef := cfg["include.path"]
	if wantDef == "" {
		if len(haveDef) > 0 {
			return true
		}
	} else {
		if len(haveDef) != 1 || haveDef[0] != wantDef {
			return true
		}
	}

	rules := accounts.FolderRules(env, list)
	condition := "gitdir:"
	if env.CaseInsensitive() {
		condition = "gitdir/i:"
	}
	includeIfCount := 0
	for k := range cfg {
		if strings.HasPrefix(k, "includeif.") && strings.HasSuffix(k, ".path") {
			includeIfCount++
		}
	}
	if includeIfCount != len(rules) {
		return true
	}
	for _, r := range rules {
		key := "includeif." + strings.ToLower(condition+r.Folder) + ".path"
		have := cfg[key]
		want := env.Shorten(env.AccountPath(r.ID))
		if len(have) != 1 || have[0] != want {
			return true
		}
	}

	signersFile, configured, err := SignersFile(env)
	if err == nil && !configured {
		hasSigners := false
		for _, a := range list {
			if a.SigningKey != "" || len(a.Retired) > 0 {
				hasSigners = true
				break
			}
		}
		haveSigners := cfg["gpg.ssh.allowedsignersfile"]
		wantSigners := ""
		if hasSigners {
			wantSigners = env.Shorten(signersFile)
		}
		if wantSigners == "" {
			if len(haveSigners) > 0 {
				return true
			}
		} else {
			if len(haveSigners) != 1 || haveSigners[0] != wantSigners {
				return true
			}
		}
	}

	return false
}
