package store

import (
	"fmt"
	"strings"

	"github.com/vehkiya/doppel/internal/accounts"
	"github.com/vehkiya/doppel/internal/paths"
)

const indexHeader = `# Generated by doppel from the files in accounts/. Don't edit this file:
# changes are overwritten. Change accounts with doppel or in accounts/<id>.gitconfig.
`

// quoteValue quotes a Git config value when it would otherwise be misread:
// "#" and ";" start comments, and surrounding spaces are trimmed.
func quoteValue(v string) string {
	if !strings.ContainsAny(v, "#;\"\\") && strings.TrimSpace(v) == v {
		return v
	}
	return `"` + strings.NewReplacer(`\`, `\\`, `"`, `\"`).Replace(v) + `"`
}

// renderIndex generates index.gitconfig: where Git finds allowed signers
// (when signersFile isn't ""), the default account, then the folder rules in
// accounts.FolderRules order. Folders are stored with a trailing "/", which
// Git extends to match every repo inside them.
func renderIndex(env *paths.Env, list []*accounts.Account, signersFile string) []byte {
	var b strings.Builder
	b.WriteString(indexHeader)
	if signersFile != "" {
		fmt.Fprintf(&b, "\n# The signing keys Git trusts when it verifies signatures\n[gpg \"ssh\"]\n\tallowedSignersFile = %s\n",
			quoteValue(env.Shorten(signersFile)))
	}
	if def := accounts.Default(list); def != nil {
		fmt.Fprintf(&b, "\n# Default account, for repos outside every folder below\n[include]\n\tpath = %s\n",
			quoteValue(env.Shorten(env.AccountPath(def.ID))))
	}

	rules := accounts.FolderRules(env, list)
	condition := "gitdir:"
	if env.CaseInsensitive() {
		condition = "gitdir/i:"
	}
	if len(rules) > 0 {
		b.WriteString("\n# Folder rules, from broad to specific (the last match wins)\n")
	}
	for _, r := range rules {
		fmt.Fprintf(&b, "[includeIf \"%s%s\"]\n\tpath = %s\n", condition, r.Folder,
			quoteValue(env.Shorten(env.AccountPath(r.ID))))
	}
	return []byte(b.String())
}

// unquoteValue reverses quoteValue for a whole-value quoted string.
func unquoteValue(v string) string {
	if len(v) < 2 || v[0] != '"' || v[len(v)-1] != '"' {
		return v
	}
	return strings.NewReplacer(`\\`, `\`, `\"`, `"`).Replace(v[1 : len(v)-1])
}
